FROM postgres:latest

# run migrations
ADD src/database/models/users/*.sql /docker-entrypoint-initdb.d/
ADD src/database/models/posts/*.sql /docker-entrypoint-initdb.d/
ADD src/database/models/tokens/*.sql /docker-entrypoint-initdb.d/

EXPOSE 5050
